# Generated by Django 4.1.3 on 2022-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rolse",
            field=models.CharField(
                choices=[
                    ("ROLE_NORMAL", "NORMAL"),
                    ("ROLE_MANAGER", "MANAGER"),
                    ("ROLE_SUPER", "SUPER"),
                ],
                default="ROLE_NORMAL",
                max_length=20,
                verbose_name="권한",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "남성(Man)"), ("W", "여성(Woman)")],
                max_length=1,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.CharField(max_length=20, verbose_name="키"),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("STOP", "STOP"),
                    ("PAUSE", "PAUSE"),
                    ("BAN", "BAN"),
                ],
                default="ACTIVE",
                max_length=10,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.CharField(max_length=16, verbose_name="몸무게"),
        ),
        migrations.DeleteModel(name="Auth",),
    ]
