# Generated by Django 4.1.3 on 2022-12-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="term_agree",
            field=models.BooleanField(default=False, verbose_name="약관동의"),
        ),
    ]
