# Generated by Django 4.1.3 on 2022-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_rolse_alter_user_gender_alter_user_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "이미 존재하는 이메일입니다."},
                max_length=255,
                unique=True,
                verbose_name="이메일",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                error_messages={"unique": "이미 존재하는 닉네임입니다."},
                max_length=16,
                unique=True,
                verbose_name="닉네임",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "이미 존재하는 아이디입니다."},
                max_length=20,
                unique=True,
                verbose_name="아이디",
            ),
        ),
    ]
