# Generated by Django 4.1.3 on 2022-12-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_creating_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='term',
        ),
    ]
