# Generated by Django 4.1.3 on 2022-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="report_point",
            field=models.PositiveIntegerField(default=0, verbose_name="신고 포인트"),
        ),
    ]
