# Generated by Django 4.1.3 on 2022-12-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=10, verbose_name="지역명")),
                ("day_date", models.CharField(max_length=10, verbose_name="날짜")),
                (
                    "day_temperature_highest",
                    models.CharField(max_length=10, verbose_name="최고기온"),
                ),
                (
                    "day_temperature_lowest",
                    models.CharField(max_length=10, verbose_name="최저기온"),
                ),
                ("day_blind", models.CharField(max_length=10, verbose_name="날씨상태")),
            ],
        ),
    ]
