# Generated by Django 4.1.3 on 2022-12-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name_kr",
                    models.CharField(max_length=50, verbose_name="브랜드명_국문"),
                ),
                (
                    "brand_name_en",
                    models.CharField(max_length=50, verbose_name="브랜드명_영문"),
                ),
                ("brand_link", models.CharField(max_length=50, verbose_name="사이트 주소")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_category_name",
                    models.CharField(max_length=50, verbose_name="메인 카테고리명"),
                ),
                (
                    "main_category_number",
                    models.IntegerField(verbose_name="메인 카테고리 번호"),
                ),
                (
                    "sub_category_name",
                    models.CharField(max_length=50, verbose_name="서브 카테고리명"),
                ),
                ("sub_category_number", models.IntegerField(verbose_name="서브 카테고리 번호")),
            ],
            options={"db_table": "Category",},
        ),
        migrations.CreateModel(
            name="ProductCategoryRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
            options={"db_table": "ProductCategoryRelation",},
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products_name", models.CharField(max_length=50, verbose_name="상품명")),
                ("original_price", models.IntegerField(verbose_name="정상가")),
                ("discount_price", models.IntegerField(verbose_name="할인가")),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="할인율"
                    ),
                ),
                ("review_count", models.IntegerField(verbose_name="리뷰")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.brand"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        through="products.ProductCategoryRelation",
                        to="products.category",
                    ),
                ),
            ],
            options={"db_table": "Products",},
        ),
        migrations.AddField(
            model_name="productcategoryrelation",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.products"
            ),
        ),
    ]
